version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network

  thdg:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
